import React from 'react';
import { StarIcon as StarIconSolid } from '@heroicons/react/24/solid';
import {
  StarIcon as StarIconOutline,
  EyeIcon,
  EyeSlashIcon,
  DocumentTextIcon,
  PlusCircleIcon,
  TrashIcon,
  PhotoIcon,
  ArrowUpTrayIcon,
  XMarkIcon,
  PaperAirplaneIcon,
  CogIcon,
  EnvelopeIcon,
  SparklesIcon,
  DocumentArrowDownIcon,
  DocumentIcon,
  ArrowLeftIcon,
  ArrowDownTrayIcon,
  DocumentChartBarIcon,
  DocumentDuplicateIcon,
  PaperClipIcon,
  CheckCircleIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  QuestionMarkCircleIcon,
  AdjustmentsHorizontalIcon,
  SquaresPlusIcon,
  PaletteIcon,
  MoonIcon,
  SunIcon,
} from '@heroicons/react/24/outline';

export const StarIcon: React.FC<React.SVGProps<SVGSVGElement> & { isFilled?: boolean }> = ({
  isFilled,
  ...props
}) => (isFilled ? <StarIconSolid {...props} /> : <StarIconOutline {...props} />);

export {
  EyeIcon,
  EyeSlashIcon,
  DocumentTextIcon,
  PlusCircleIcon,
  TrashIcon,
  PhotoIcon,
  ArrowUpTrayIcon,
  XMarkIcon,
  PaperAirplaneIcon,
  CogIcon,
  EnvelopeIcon,
  SparklesIcon,
  DocumentArrowDownIcon,
  DocumentIcon,
  ArrowLeftIcon,
  ArrowDownTrayIcon,
  DocumentChartBarIcon,
  DocumentDuplicateIcon,
  PaperClipIcon,
  CheckCircleIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  QuestionMarkCircleIcon,
  AdjustmentsHorizontalIcon,
  SquaresPlusIcon,
  PaletteIcon,
  MoonIcon,
  SunIcon,
};
