# Documentation: https://github.com/agattone96/ideaforge/blob/main/README.md#continuous-integration
name: Accessibility Test

on:
  push:
    branches: [ main ]
    paths: [ 'src/**', 'public/**' ]
  pull_request:
    branches: [ main ]
concurrency:
  group: accessibility-test-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  axe:
    name: Run axe Accessibility Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Start app in background
        run: npm run start &> /dev/null &

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000

      - name: Run axe-core scan
        run: npx axe http://localhost:3000 --save results.json

      - name: Upload accessibility report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: accessibility-report
          path: results.json