# Documentation: https://github.com/agattone96/ideaforge/blob/main/README.md#continuous-integration
name: Coverage Comment

on:
  workflow_run:
    workflows: [ CI ]
    types: [ completed ]
concurrency:
  group: coverage-comment-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  checks: write

jobs:
  comment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Post Coverage to PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Post coverage report via Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true