# Documentation: https://github.com/agattone96/ideaforge/blob/main/README.md#continuous-integration
name: Dependency Update

on:
  schedule:
    - cron: '0 4 * * 0'  # weekly on Sunday at 04:00 UTC
  workflow_dispatch:
concurrency:
  group: dependency-update
  cancel-in-progress: true
permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    name: Bump Dependencies & Create PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm

      - name: Bump dependencies
        run: |
          npm install -g npm-check-updates
          ncu -u

      - name: Install updated dependencies
        run: npm ci

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: chore(deps): bump dependencies
          branch: dependency-update
          title: chore(deps): scheduled dependency update
          labels: dependencies, automated
