name: Docker Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    name: Scan Docker Image with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ideaforge:latest .

      - name: Scan image
        uses: aquasecurity/trivy-action@v0.9
        with:
          image-ref: ideaforge:latest
          format: table
          exit-code: 1
          vuln-type: 'os,library'