# Documentation: https://github.com/agattone96/ideaforge/blob/main/README.md#continuous-integration
name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  build:
    name: Build & Archive Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ideaforge:${{ github.sha }} .

      - name: Save image as artifact
        run: |
          mkdir -p artifacts
          docker save ideaforge:${{ github.sha }} | gzip > artifacts/ideaforge_${{ github.sha }}.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ github.sha }}
          path: artifacts/
