name: Docker Publish

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  publish:
    name: Build & Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{
              secrets.DOCKERHUB_USERNAME
            }}/ideaforge:latest
            ${{
              secrets.DOCKERHUB_USERNAME
            }}/ideaforge:${{ github.ref_name }}