# Documentation: https://github.com/agattone96/ideaforge/blob/main/README.md#continuous-integration
name: Docker Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
concurrency:
  group: docker-scan-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  trivy-scan:
    name: Scan Docker Image with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ideaforge:latest .

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@v0.9
        with:
          image-ref: ideaforge:latest
          format: table
          exit-code: 1
          vuln-type: os,library
