name: Helm Chart Lint

on:
  pull_request:
    paths:
      - 'charts/**'

jobs:
  lint:
    name: Lint Helm Charts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout charts
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Lint all charts
        run: helm lint charts/