name: Infrastructure Lint

on:
  push:
    paths:
      - 'infrastructure/**'

jobs:
  terraform-check:
    name: Terraform fmt & validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'

      - name: Check formatting
        run: terraform fmt -check

      - name: Validate configuration
        run: terraform validate

      - name: Run TFLint
        uses: terraform-linters/tflint-action@v2