name: Performance Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Start app
        run: npm run start &> /dev/null &

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@9
        with:
          urls: http://localhost:3000
          configPath: .lighthouserc.js