name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          node-version: '18.x'
          npm_token: ${{ secrets.NPM_TOKEN }}