name: Secret Scanning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 1 * * *'  # Daily at 01:00 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  detect-secrets:
    name: Detect Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install detect-secrets
        run: pip install detect-secrets

      - name: Scan for secrets
        run: |
          # Update or generate baseline, then audit
          detect-secrets scan --update .secrets.baseline || true
          detect-secrets audit .secrets.baseline

      - name: Upload baseline
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: secrets-baseline
          path: .secrets.baseline