# Documentation: https://github.com/agattone96/ideaforge/blob/main/README.md#continuous-integration
name: Security Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: security-audit-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  npm-audit:
    name: NPM Vulnerability Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit (moderate & above)
        run: npm audit --audit-level=moderate --json > audit.json

      - name: Upload audit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: audit.json

      - name: Display audit summary
        if: always()
        run: cat audit.json
