name: Terraform Apply

on:
  push:
    branches: [ main ]
    paths:
      - 'infrastructure/**/*.tf'

jobs:
  apply:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout infra
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve